CREATE OR REPLACE PROCEDURE SNOWFLAKE_SANDBOX_DB.PUBLIC.TEST_TABLE_ON_THE_FLY(table_name VARCHAR)
  RETURNS TABLE(N_NAME VARCHAR(1000))
  LANGUAGE SQL
AS
DECLARE
  res RESULTSET;
  query VARCHAR DEFAULT 'select N_NAME from IDENTIFIER(?) where N_NATIONKEY = 0;';
BEGIN
  res := (EXECUTE IMMEDIATE :query USING(table_name));
  RETURN TABLE(res);
END;


CALL SNOWFLAKE_SANDBOX_DB.PUBLIC.TEST_TABLE_ON_THE_FLY(SELECT TO_VARCHAR('SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.' || KeyColumn) from SNOWFLAKE_SANDBOX_DB.PUBLIC.ALGERIA where ID = :year);